"""Purpose attr

Revision ID: 4a8f7e98ecac
Revises: af5a19e9b6e8
Create Date: 2025-09-17 21:18:16.186526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a8f7e98ecac'
down_revision: Union[str, Sequence[str], None] = 'af5a19e9b6e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trip', 'journey_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trip', 'journey_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
