"""Relation Update: User

Revision ID: 61c167754b7a
Revises: 927cf9e6bf14
Create Date: 2025-09-20 16:49:38.793160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61c167754b7a'
down_revision: Union[str, Sequence[str], None] = '927cf9e6bf14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'consent_end_time')
    op.drop_column('user', 'consent_start_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('consent_start_time', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('consent_end_time', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
