"""Relation: DataCollector

Revision ID: 927cf9e6bf14
Revises: 21e4f8606c78
Create Date: 2025-09-20 16:20:46.176314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '927cf9e6bf14'
down_revision: Union[str, Sequence[str], None] = '21e4f8606c78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_collector', 'is_added_to_trip')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_collector', sa.Column('is_added_to_trip', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
