"""Added extra Relations

Revision ID: aa40f29cd549
Revises: 7cbe54e516ee
Create Date: 2025-09-14 11:15:52.410346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa40f29cd549'
down_revision: Union[str, Sequence[str], None] = '7cbe54e516ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('location_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_points_id'), 'location_points', ['id'], unique=False)
    op.create_table('estimated_route_time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin_location_id', sa.Integer(), nullable=True),
    sa.Column('destination_location_id', sa.Integer(), nullable=True),
    sa.Column('mode_id', sa.Integer(), nullable=True),
    sa.Column('estimated_duration_minutes', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['destination_location_id'], ['location_points.id'], ),
    sa.ForeignKeyConstraint(['mode_id'], ['trip_mode.id'], ),
    sa.ForeignKeyConstraint(['origin_location_id'], ['location_points.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estimated_route_time_id'), 'estimated_route_time', ['id'], unique=False)
    op.add_column('trip', sa.Column('origin_location_id', sa.Integer(), nullable=True))
    op.add_column('trip', sa.Column('destination_location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'trip', 'location_points', ['origin_location_id'], ['id'])
    op.create_foreign_key(None, 'trip', 'location_points', ['destination_location_id'], ['id'])
    op.drop_column('trip', 'destination_lat')
    op.drop_column('trip', 'origin_lat')
    op.drop_column('trip', 'destination_lon')
    op.drop_column('trip', 'origin_lon')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip', sa.Column('origin_lon', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('trip', sa.Column('destination_lon', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('trip', sa.Column('origin_lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('trip', sa.Column('destination_lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'trip', type_='foreignkey')
    op.drop_constraint(None, 'trip', type_='foreignkey')
    op.drop_column('trip', 'destination_location_id')
    op.drop_column('trip', 'origin_location_id')
    op.drop_index(op.f('ix_estimated_route_time_id'), table_name='estimated_route_time')
    op.drop_table('estimated_route_time')
    op.drop_index(op.f('ix_location_points_id'), table_name='location_points')
    op.drop_table('location_points')
    # ### end Alembic commands ###
