"""Pupose of trip

Revision ID: af5a19e9b6e8
Revises: 5d9867cd1bbe
Create Date: 2025-09-16 21:42:31.838913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af5a19e9b6e8'
down_revision: Union[str, Sequence[str], None] = '5d9867cd1bbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip', sa.Column('purpose', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trip', 'purpose')
    # ### end Alembic commands ###
