"""Time->str

Revision ID: bf39be51794f
Revises: 4a8f7e98ecac
Create Date: 2025-09-17 22:54:03.979124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf39be51794f'
down_revision: Union[str, Sequence[str], None] = '4a8f7e98ecac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('complaint', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('trip', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('trip', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('user', 'consent_start_time',
               existing_type=postgresql.TIME(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('user', 'consent_end_time',
               existing_type=postgresql.TIME(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'consent_end_time',
               existing_type=sa.String(),
               type_=postgresql.TIME(),
               existing_nullable=False)
    op.alter_column('user', 'consent_start_time',
               existing_type=sa.String(),
               type_=postgresql.TIME(),
               existing_nullable=False)
    op.alter_column('trip', 'end_time',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('trip', 'start_time',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('complaint', 'timestamp',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
