"""Relation: Journey

Revision ID: d5980a093659
Revises: 61c167754b7a
Create Date: 2025-09-20 16:59:39.654175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5980a093659'
down_revision: Union[str, Sequence[str], None] = '61c167754b7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(), nullable=True),
    sa.Column('destination', sa.String(), nullable=True),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('is_verified_by_user', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journey_id'), 'journey', ['id'], unique=False)
    op.create_foreign_key(None, 'trip', 'journey', ['journey_id'], ['id'], ondelete='CASCADE')
    op.drop_column('trip', 'is_verified_by_user')
    op.drop_column('trip', 'purpose')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip', sa.Column('purpose', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('trip', sa.Column('is_verified_by_user', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'trip', type_='foreignkey')
    op.drop_index(op.f('ix_journey_id'), table_name='journey')
    op.drop_table('journey')
    # ### end Alembic commands ###
