"""FK user_id in Journey

Revision ID: fdbc52e52c44
Revises: 6e753643a6f0
Create Date: 2025-09-20 22:10:47.570035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdbc52e52c44'
down_revision: Union[str, Sequence[str], None] = '6e753643a6f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journey', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'journey', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'journey', type_='foreignkey')
    op.drop_column('journey', 'user_id')
    # ### end Alembic commands ###
