"""start and end time in Journey Relation

Revision ID: 1c9426d78cd3
Revises: 7b26fb77f49f
Create Date: 2025-09-21 20:43:10.497340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c9426d78cd3'
down_revision: Union[str, Sequence[str], None] = '7b26fb77f49f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journey', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.add_column('journey', sa.Column('end_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journey', 'end_time')
    op.drop_column('journey', 'start_time')
    # ### end Alembic commands ###
